export const translations = {
  es: {
      nav_home: "Inicio",
      nav_services: "Servicios",
      nav_portfolio: "Portafolio",
      nav_testimonials: "Testimonios",
      nav_about: "Sobre Mí",
      nav_contact: "Hablemos",
      hero_subtitle: "Full-Stack Digital Strategist ✨",
      hero_title: "Desarrollo web y estrategia digital que <span>convierten usuarios en clientes.</span>",
      hero_desc: "Soy Frontend Developer & Community Manager. Combino código limpio con estrategias de marketing para crear productos digitales que no solo se ven bien, sino que generan resultados.",
      hero_cta: "Iniciar mi Proyecto",
      hero_sec_cta: "Descubrir mis servicios",
      services_title: "Mis Servicios",
      services_subtitle: "Soluciones integrales de alto impacto para negocios modernos.",
      serv1_title: "1. Desarrollo de Software",
      serv1_desc: "Diseño de Landing Pages para captación, portafolios digitales inmersivos y optimización extrema de sitios web para máxima velocidad y retención (Frontend UI/UX).",
      serv2_title: "2. Marketing & Contenidos",
      serv2_desc: "Gestión estratégica integral de redes: calendarios de contenido, creación de piezas visuales coherentes con tu marca y consultoría para tiendas E-commerce.",
      serv3_title: "3. Innovación con I.A.",
      serv3_desc: "Consultoría en creación de avatares/modelos generados por IA para marcas, voces sintetizadas, y estructuración automatizada de ebooks o infoproductos.",
      port_title: "Proyectos Destacados",
      port_subtitle: "Una selección de mis mejores trabajos y casos de éxito reales.",
      filter_all: "Todos",
      filter_dev: "Web / Código",
      filter_social: "Social Media & Diseño",
      filter_media: "Multimedia (Video & Audio)",
      workflow_title: "Mi Proceso de Trabajo",
      workflow_subtitle: "Metodología probada para transformar tu visión en resultados comerciales.",
      workflow_s1_title: "1. Descubrimiento y Estrategia",
      workflow_s1_desc: "Entiendo a fondo tu modelo de negocio, tus clientes ideales y tus objetivos comerciales para definir una hoja de ruta clara.",
      workflow_s2_title: "2. Diseño UI/UX",
      workflow_s2_desc: "Creo prototipos interactivos centrados en la retención del usuario, garantizando que tu producto sea intuitivo y atractivo.",
      workflow_s3_title: "3. Desarrollo Técnico",
      workflow_s3_desc: "Escribo código limpio, rápido y escalable. Construyo plataformas robustas con las últimas tecnologías web para máxima velocidad.",
      workflow_s4_title: "4. Lanzamiento y Crecimiento",
      workflow_s4_desc: "Despliego tu producto y ejecuto estrategias de marketing para asegurar que empiece a generar ventas e interacciones desde el día 1.",
      port_view: "Visitar Proyecto",
      value_title: "¿Por qué un <span>desarrollador y estratega integral</span> es tu mejor inversión?",
      value_desc1: "El problema de contratar múltiples agencias o freelancers por separado es la falta de comunicación. El diseñador no entiende de código, y el programador no sabe de marketing. Eso agota tu presupuesto y retrasa lanzamientos.",
      value_desc2: "Yo cierro esa brecha. Al unificar el desarrollo técnico (sitios web rápidos y funcionales) con la estrategia digital (redes sociales y contenidos), entrego productos listos para generar resultados comerciales reales desde el primer día.",
      stat1: "Enfoque en Conversión",
      stat2: "Más Rapidez",
      test_title: "Lo que dicen mis clientes",
      test_subtitle: "Resultados reales para negocios reales.",
      test1_quote: '"Tiene una habilidad única para conectar con la audiencia. Además, sus conocimientos en programación fueron clave para optimizar nuestras plataformas digitales."',
      test1_role: "Forrajeria Mis Consentidos",
      test2_quote: '"Su capacidad para manejar tanto la gestión de comunidades como el desarrollo técnico con tanta soltura es realmente inspiradora. ¡Un gran aporte!"',
      test2_role: "Estudio Jurídico Idiart Troglia",
      test3_quote: '"Hernán es un crack total. Llevó nuestra presencia en redes a otro nivel, y su expertise nos permitió implementar soluciones innovadoras."',
      test3_role: "Femmina LAB",
      test4_quote: '"Su atención al detalle y habilidad para manejar múltiples tareas es impresionante. Siempre entrega alta calidad. Muy recomendable."',
      test4_role: "AETTECH",
      test5_quote: '"Increíble el trabajo que hizo con nuestra web. No solo quedó estéticamente impecable, sino que además empezó a generar ventas desde la primera semana."',
      test5_role: "TechNova Soluciones",
      test6_quote: '"Tercer proyecto que lanzo junto a él y siempre supera mis expectativas. El código es impecable y entiende perfectamente cómo vender un producto."',
      test6_role: "Vanguardia Growth",
      about_title: "Un poco más sobre mí",
      about_p1: "Hola, soy Hernán Francini, profesional radicado en Córdoba, Argentina. Mi mayor ventaja competitiva es que hablo dos idiomas: el técnico (código) y el comercial (marketing).",
      about_p2: "Como Frontend Developer y Community Manager, no solo construyo sitios web rápidos y modernos con React, sino que entiendo cómo estructurarlos para retener usuarios, generar leads y potenciar marcas en redes sociales. Cierro la brecha entre el desarrollo técnico y la estrategia de negocio.",
      about_highlight: "Mi misión es simple: asegurarme de que mi cliente gane más de lo que invierte en mí.",
      about_cv_dev: "CV Desarrollador Frontend",
      about_cv_cm: "CV Community Manager & Marketing",
      faq_title: "Preguntas Frecuentes",
      faq_subtitle: "Resolvemos tus dudas antes de empezar.",
      cta_title: "¿Listo para transformar tu proyecto?",
      cta_subtitle: "Hablemos de tus metas comerciales y de cómo la tecnología exacta puede ayudarte a alcanzarlas.",
      cta_btn: "Hablemos por WhatsApp",
      contact_subtitle: "Contacto",
      contact_title: "Hablemos de tu proyecto",
      contact_info_title: "Contacto Directo",
      contact_info_desc: "Completa el formulario para una propuesta detallada o escríbeme por redes sociales para respuestas más rápidas.",
      contact_location: "Ubicación",
      form_name: "Nombre Completo",
      form_email: "Correo Electrónico",
      form_message: "Mensaje / Detalles del Proyecto",
      form_submit: "Enviar Mensaje",
      form_success: "✅ ¡Mensaje enviado con éxito! Te responderé pronto.",
      form_error: "❌ Ocurrió un error al enviar el formulario.",
      skills_title: "Mi Stack Tecnológico",
      skills_subtitle: "Habilidades y tecnologías organizadas por especialidad técnica",
      skills_cat_frontend: "Desarrollo Frontend",
      skills_cat_frontend_desc: "Interfaces modernas, dinámicas y de alto rendimiento.",
      skills_cat_backend: "Backend & Datos",
      skills_cat_backend_desc: "APIs robustas, persistencia y gestión de estado.",
      skills_cat_tools: "Herramientas & Cloud",
      skills_cat_tools_desc: "Control de versiones, despliegue continuo y tooling moderno.",
      skills_cat_design: "Diseño UI/UX & Branding",
      skills_cat_design_desc: "Prototipado interactivo, identidad de marca y sistemas visuales.",
      skills_cat_ai: "I.A. & Automatización",
      skills_cat_ai_desc: "Integración de modelos generativos y flujos automatizados.",
      skills_cat_marketing: "Marketing & Multimedia",
      skills_cat_marketing_desc: "Estrategias de conversión, pauta publicitaria y producción.",
      skill_react_title: "React.js",
      skill_react_desc: "Aplicaciones web ágiles estructuradas por componentes modulares.",
      skill_next_title: "Next.js (App Router)",
      skill_next_desc: "Server Components, renderizado híbrido y optimización de rendimiento.",
      skill_ts_title: "TypeScript",
      skill_ts_desc: "Tipado estático para código robusto, predecible y escalable.",
      skill_js_title: "JavaScript (ES6+)",
      skill_js_desc: "Lógica asíncrona avanzada, manipulación del DOM y arquitecturas limpias.",
      skill_tailwind_title: "Tailwind CSS",
      skill_tailwind_desc: "Maquetación utilitaria, diseño Glassmorphism y temas responsivos.",
      skill_framer_title: "Framer Motion",
      skill_framer_desc: "Animaciones fluidas, micro-interacciones y transiciones UI complejas.",
      skill_html_title: "HTML5 & CSS3",
      skill_html_desc: "Estructura semántica, accesibilidad y maquetación web responsiva.",
      skill_node_title: "Node.js & Express",
      skill_node_desc: "Desarrollo de servicios backend, middlewares y lógica de servidor.",
      skill_api_title: "APIs RESTful",
      skill_api_desc: "Conexión fluida con servicios externos, manejo asíncrono y endpoints.",
      skill_supabase_title: "Supabase / PostgreSQL",
      skill_supabase_desc: "Bases de datos relacionales, autenticación segura y políticas RLS.",
      skill_state_title: "Zustand & State",
      skill_state_desc: "Gestión global de estado optimista, atómica y persistente.",
      skill_dexie_title: "Dexie.js / IndexedDB",
      skill_dexie_desc: "Almacenamiento local persistente y operaciones offline ultra-rápidas.",
      skill_stripe_title: "Stripe Payments",
      skill_stripe_desc: "Integración de pasarelas de cobro seguras y flujo de checkout.",
      skill_git_title: "Git & GitHub",
      skill_git_desc: "Control de versiones profesional, flujo de ramas y colaboración.",
      skill_vercel_title: "Vercel & Netlify",
      skill_vercel_desc: "Despliegue continuo (CI/CD), variables de entorno y hosting Edge.",
      skill_vite_title: "Vite & Tooling",
      skill_vite_desc: "Compilación ultra-rápida, empaquetado optimizado y desarrollo ágil.",
      skill_seo_title: "SEO & Core Web Vitals",
      skill_seo_desc: "Optimización extrema para velocidad de carga y posicionamiento web.",
      skill_figma_title: "Figma (UI/UX)",
      skill_figma_desc: "Wireframes, prototipos de alta fidelidad y design systems.",
      skill_canva_title: "Canva Pro & Branding",
      skill_canva_desc: "Creación de piezas gráficas visuales y manuales de identidad.",
      skill_ai_title: "Gemini & OpenAI APIs",
      skill_ai_desc: "Integración de LLMs multimodales, structured output y prompt engineering.",
      skill_workflow_title: "Automatizaciones I.A.",
      skill_workflow_desc: "Optimización de flujos de trabajo inteligentes y generación de contenido.",
      skill_meta_title: "Meta Ads (FB & IG)",
      skill_meta_desc: "Campañas orientadas a retorno de inversión (ROI) y conversión de clientes.",
      skill_video_title: "Edición de Video",
      skill_video_desc: "Edición dinámica en CapCut con subtítulos animados de alta retención.",
      skill_audio_title: "Producción de Audio",
      skill_audio_desc: "Locución profesional, jingles e identidad auditiva para marcas.",
      skill_copy_title: "Copywriting Persuasivo",
      skill_copy_desc: "Ganchos magnéticos, storytelling y textos comerciales que convierten.",
      footer_location: "Córdoba, Argentina.",
      footer_rights: "© 2026 Hernán Francini. Todos los derechos reservados."
  },
  en: {
      nav_home: "Home",
      nav_services: "Services",
      nav_portfolio: "Portfolio",
      nav_testimonials: "Testimonials",
      nav_about: "About Me",
      nav_contact: "Let's Talk",
      hero_subtitle: "Full-Stack Digital Strategist",
      hero_title: "I design digital experiences that <span>elevate your brand</span> and attract real clients.",
      hero_desc: "Strategic web development and community management to position you as an industry leader.",
      hero_cta: "Start My Project",
      hero_sec_cta: "Discover My Services",
      services_title: "My Services",
      services_subtitle: "High-impact integral solutions for modern businesses.",
      serv1_title: "1. Software Development",
      serv1_desc: "Design of high-converting Landing Pages, immersive digital portfolios, and extreme website optimization for maximum speed and retention (Frontend UI/UX).",
      serv2_title: "2. Marketing & Content",
      serv2_desc: "Comprehensive social media strategy management: content calendars, visual creation aligned with your brand, and consulting for E-commerce stores.",
      serv3_title: "3. A.I. Innovation",
      serv3_desc: "Consulting on AI-generated avatars/models for brands, synthesized voices, and automated structuring of ebooks or infoproducts.",
      port_title: "Featured Projects",
      port_subtitle: "A selection of my best work and real success stories.",
      filter_all: "All",
      filter_dev: "Web / Code",
      filter_social: "Social Media & Design",
      filter_media: "Multimedia (Video & Audio)",
      workflow_title: "My Workflow",
      workflow_subtitle: "Proven methodology to transform your vision into commercial results.",
      workflow_s1_title: "1. Discovery & Strategy",
      workflow_s1_desc: "I deeply understand your business model, your ideal clients, and your commercial goals to define a clear roadmap.",
      workflow_s2_title: "2. UI/UX Design",
      workflow_s2_desc: "I create interactive prototypes focused on user retention, ensuring your product is intuitive and visually appealing.",
      workflow_s3_title: "3. Technical Development",
      workflow_s3_desc: "I write clean, fast, and scalable code. Building robust platforms with the latest web technologies for maximum speed.",
      workflow_s4_title: "4. Launch & Growth",
      workflow_s4_desc: "I deploy your product and execute marketing strategies to ensure it starts generating sales and interactions from day 1.",
      port_view: "Visit Project",
      value_title: "Why a <span>full-stack developer & strategist</span> is your best investment?",
      value_desc1: "The problem with hiring multiple separate agencies or freelancers is the lack of alignment. The designer doesn't understand code, and the developer doesn't know marketing. That drains your budget and delays launches.",
      value_desc2: "I close that gap. By unifying frontend development (fast, responsive websites) with digital strategy (social media and content creation), I deliver ready-to-scale products that drive commercial results from day one.",
      stat1: "Conversion Focus",
      stat2: "Faster Delivery",
      test_title: "What my clients say",
      test_subtitle: "Real results for real businesses.",
      test1_quote: '"Has a unique ability to connect with the audience. Furthermore, his programming knowledge was key to optimizing our digital platforms."',
      test1_role: "Forrajeria Mis Consentidos",
      test2_quote: '"His ability to handle both community management and technical development with such ease is truly inspiring. A great asset!"',
      test2_role: "Estudio Jurídico Idiart Troglia",
      test3_quote: '"Hernán is an absolute rockstar. He took our social media presence to another level, and his expertise allowed us to implement innovative solutions."',
      test3_role: "Femmina LAB",
      test4_quote: '"His attention to detail and ability to handle multiple tasks is impressive. Always delivers high quality. Highly recommended."',
      test4_role: "AETTECH",
      test5_quote: '"Incredible work on our website. Not only was it aesthetically flawless, but it also started generating sales from the very first week."',
      test5_role: "TechNova Solutions",
      test6_quote: '"Third project I launch with him, and he always exceeds my expectations. The code is impeccable and he perfectly understands how to sell a product."',
      test6_role: "Vanguardia Growth",
      about_title: "A little more about me",
      about_p1: "Hi, I'm Hernán Francini, a professional based in Córdoba, Argentina. My passion has always been finding the exact point where visual creativity collides with perfect technical logic.",
      about_p2: "After years of perfecting myself in both software development (Frontend) and digital communication (Community Management, Copywriting, Video Editing), I've built a unique profile ready to tackle end-to-end digital challenges.",
      about_highlight: "My mission is simple: to make sure my client earns more than they invest in me.",
      about_cv_dev: "Frontend Developer CV",
      about_cv_cm: "Community Manager CV",
      faq_title: "Frequently Asked Questions",
      faq_subtitle: "Answering your doubts before we start.",
      cta_title: "Ready to transform your project?",
      cta_subtitle: "Let's talk about your commercial goals and how the exact technology can help you achieve them.",
      cta_btn: "Let's talk on WhatsApp",
      contact_subtitle: "Contact",
      contact_title: "Let's talk about your project",
      contact_info_title: "Direct Contact",
      contact_info_desc: "Fill out the form for a detailed quote or write to me on social networks for faster replies.",
      contact_location: "Location",
      form_name: "Full Name",
      form_email: "Email Address",
      form_message: "Message / Project Details",
      form_submit: "Send Message",
      form_success: "✅ Message sent successfully! I will reply soon.",
      form_error: "❌ An error occurred while sending the form.",
      skills_title: "My Tech Stack",
      skills_subtitle: "Skills and technologies organized by technical specialty",
      skills_cat_frontend: "Frontend Development",
      skills_cat_frontend_desc: "Modern, dynamic, and high-performance user interfaces.",
      skills_cat_backend: "Backend & Data",
      skills_cat_backend_desc: "Robust APIs, persistence, and state management.",
      skills_cat_tools: "Tools & Cloud",
      skills_cat_tools_desc: "Version control, continuous deployment, and modern tooling.",
      skills_cat_design: "UI/UX Design & Branding",
      skills_cat_design_desc: "Interactive prototyping, brand identity, and design systems.",
      skills_cat_ai: "A.I. & Automation",
      skills_cat_ai_desc: "Generative model integration and automated workflows.",
      skills_cat_marketing: "Marketing & Multimedia",
      skills_cat_marketing_desc: "Conversion strategies, paid campaigns, and production.",
      skill_react_title: "React.js",
      skill_react_desc: "Fast, component-based web applications with high modularity.",
      skill_next_title: "Next.js (App Router)",
      skill_next_desc: "Server Components, hybrid rendering, and performance optimization.",
      skill_ts_title: "TypeScript",
      skill_ts_desc: "Static typing for robust, predictable, and scalable codebases.",
      skill_js_title: "JavaScript (ES6+)",
      skill_js_desc: "Advanced async logic, DOM manipulation, and clean architecture.",
      skill_tailwind_title: "Tailwind CSS",
      skill_tailwind_desc: "Utility-first layout, Glassmorphism, and responsive themes.",
      skill_framer_title: "Framer Motion",
      skill_framer_desc: "Smooth animations, micro-interactions, and complex UI physics.",
      skill_html_title: "HTML5 & CSS3",
      skill_html_desc: "Semantic markup, web accessibility, and responsive layouts.",
      skill_node_title: "Node.js & Express",
      skill_node_desc: "Creation of scalable backend services, middlewares, and APIs.",
      skill_api_title: "RESTful APIs",
      skill_api_desc: "Seamless third-party integrations, async handlers, and endpoints.",
      skill_supabase_title: "Supabase / PostgreSQL",
      skill_supabase_desc: "Relational databases, secure authentication, and RLS policies.",
      skill_state_title: "Zustand & State",
      skill_state_desc: "Optimistic, atomic, and persistent global state management.",
      skill_dexie_title: "Dexie.js / IndexedDB",
      skill_dexie_desc: "Client-side offline data persistence and ultra-fast indexing.",
      skill_stripe_title: "Stripe Payments",
      skill_stripe_desc: "Secure payment gateway integration and automated checkout flows.",
      skill_git_title: "Git & GitHub",
      skill_git_desc: "Professional version control, branching workflows, and PRs.",
      skill_vercel_title: "Vercel & Netlify",
      skill_vercel_desc: "Continuous deployment (CI/CD), environment management, and Edge hosting.",
      skill_vite_title: "Vite & Tooling",
      skill_vite_desc: "Ultra-fast bundling, modern HMR, and agile asset management.",
      skill_seo_title: "SEO & Core Web Vitals",
      skill_seo_desc: "Extreme optimization for load speed, UX metrics, and search ranking.",
      skill_figma_title: "Figma (UI/UX)",
      skill_figma_desc: "Wireframes, high-fidelity prototypes, and design systems.",
      skill_canva_title: "Canva Pro & Branding",
      skill_canva_desc: "Creation of visual brand assets and comprehensive style guides.",
      skill_ai_title: "Gemini & OpenAI APIs",
      skill_ai_desc: "Multimodal LLM integration, structured output, and prompt engineering.",
      skill_workflow_title: "A.I. Automations",
      skill_workflow_desc: "Intelligent workflow automation and generative content pipelines.",
      skill_meta_title: "Meta Ads (FB & IG)",
      skill_meta_desc: "High-ROI conversion campaigns on Instagram and Facebook.",
      skill_video_title: "Video Editing",
      skill_video_desc: "Dynamic edits in CapCut featuring high-retention animated subtitles.",
      skill_audio_title: "Audio Production",
      skill_audio_desc: "Professional voice-over, jingles, and sonic branding for ads.",
      skill_copy_title: "Persuasive Copywriting",
      skill_copy_desc: "Magnetic hooks, commercial storytelling, and high-converting copy.",
      footer_location: "Córdoba, Argentina.",
      footer_rights: "© 2026 Hernán Francini. All rights reserved."
  }
};

export const projects = [
  {
    category: "dev",
    github: "https://github.com/Sherfran89/nexus-ai",
    image: "/assets/mockup_nexus_ai.png",
    link: "https://github.com/Sherfran89/nexus-ai",
    title: { es: "Nexus AI Content Gen", en: "Nexus AI Content Gen" },
    desc: { es: "Aplicación web para generación inteligente de contenidos de marketing digital con IA (Google Gemini), optimización multi-plataforma y almacenamiento local seguro.", en: "AI-powered marketing content generation web app (Google Gemini) with multi-platform optimization and secure local storage." }
  },
  {
    category: "dev",
    github: "https://github.com/Sherfran89/ecommerce-headless-pro",
    image: "/assets/mockup_ecommerce_headless.png",
    link: "https://github.com/Sherfran89/ecommerce-headless-pro",
    title: { es: "E-Commerce Headless Pro", en: "E-Commerce Headless Pro" },
    desc: { es: "Plataforma de comercio electrónico de alto rendimiento con arquitectura Headless, Next.js 15, React 19, Zustand, integración con Stripe y Tailwind CSS v4.", en: "High-performance Headless e-commerce platform built with Next.js 15, React 19, Zustand, Stripe integration, and Tailwind CSS v4." }
  },
  {
    category: "dev",
    github: "https://github.com/Sherfran89/realtime-productivity-board",
    image: "/assets/mockup_productivity_board.png",
    link: "https://github.com/Sherfran89/realtime-productivity-board",
    title: { es: "Productivity Board", en: "Productivity Board" },
    desc: { es: "Tablero de gestión de tareas interactivo estilo Trello/Notion con Drag & Drop avanzado (@dnd-kit), indexación fraccional y estado optimista con Zustand.", en: "Interactive Trello/Notion-style task board with advanced Drag & Drop (@dnd-kit), fractional indexing, and optimistic UI with Zustand." }
  },
  {
    category: "dev",
    github: "https://github.com/Sherfran89/dashboard-financiero",
    image: "/assets/mockup_dashboard_financiero.png",
    link: "https://github.com/Sherfran89/dashboard-financiero",
    title: { es: "Dashboard Financiero", en: "Financial Dashboard" },
    desc: { es: "Panel analítico y financiero interactivo con métricas en tiempo real, gráficos dinámicos con Recharts y gestión de estado global con Zustand.", en: "Interactive financial and analytics dashboard featuring real-time metrics, dynamic charts with Recharts, and Zustand state management." }
  },
  {
    category: "dev",
    github: "https://github.com/Sherfran89/Mario-Game",
    image: "/assets/mockup_mario.png",
    link: "https://sherfran89.github.io/Mario-Game/",
    title: { es: "Mario Game", en: "Mario Game" },
    desc: { es: "Juego clásico interactivo de Mario Bros desarrollado con HTML5, animaciones CSS y JavaScript para detección de colisiones y manipulación del DOM.", en: "Classic interactive Mario Bros game developed with HTML5, CSS animations, and JavaScript collision detection and DOM manipulation." }
  },
  {
    category: "dev",
    github: "https://github.com/Sherfran89/calculator",
    image: "/assets/mockup_calculadora.png",
    link: "https://sherfran89.github.io/calculator/",
    title: { es: "Calculadora Web", en: "Web Calculator" },
    desc: { es: "Calculadora interactiva con diseño responsive, operaciones matemáticas encadenadas y estética moderna en CSS3 y JavaScript.", en: "Interactive responsive web calculator with chained mathematical operations and modern CSS3 and JavaScript UI." }
  },
  {
    category: "dev",
    github: "#",
    image: "/assets/mockup_pixelstudio.png",
    link: "https://pixelstudiocba.netlify.app",
    title: { es: "Pixel Studio", en: "Pixel Studio" },
    desc: { es: "Landing Page de alta conversión para estudio creativo. Optimizada para cargar en menos de 1 segundo (React + Framer Motion).", en: "High-converting Landing Page for a creative studio. Optimized for sub-second load times (React + Framer Motion)." }
  },
  {
    category: "dev",
    github: "#",
    image: "/assets/mockup_astroweb.png",
    link: "https://astrologiaweb.netlify.app",
    title: { es: "Astrología Web", en: "Astrology Web" },
    desc: { es: "Plataforma SaaS interactiva con procesamiento de datos en tiempo real. Interfaz dinámica diseñada para maximizar la retención de usuarios.", en: "Interactive SaaS platform with real-time data processing. Dynamic interface designed to maximize user retention." }
  },
  {
    category: "dev",
    github: "#",
    image: "/assets/mockup_eternia.png",
    link: "https://eterniaonline.netlify.app",
    title: { es: "Eternia Online", en: "Eternia Online" },
    desc: { es: "Sitio corporativo inmersivo enfocado en captación de leads y comunidad. Maquetación semántica con métricas perfectas de SEO.", en: "Immersive corporate site focused on lead generation and community. Semantic layout with perfect SEO metrics." }
  },
  {
    category: "dev",
    github: "#",
    image: "/assets/mockup_xeneize.png",
    link: "https://xeneizehub.netlify.app",
    title: { es: "Xeneize Hub", en: "Xeneize Hub" },
    desc: { es: "Dashboard analítico B2B para visualización de datos estadísticos complejos mediante una interfaz intuitiva y responsive.", en: "B2B analytical dashboard for complex statistical data visualization through an intuitive and responsive interface." }
  },
  {
    category: "dev",
    github: "#",
    image: "/assets/mockup_pelisreco.png",
    link: "https://pelis-reco.netlify.app",
    title: { es: "Pelis Reco", en: "Pelis Reco" },
    desc: { es: "Aplicación de consumo de APIs a gran escala con búsquedas asíncronas y arquitectura frontend escalable.", en: "Large-scale API consumption application with asynchronous searches and scalable frontend architecture." }
  },
  {
    category: "dev",
    github: "#",
    image: "/assets/mockup_compraloYa.png",
    link: "https://compraloya-shop.netlify.app",
    title: { es: "CompraloYa Shop", en: "CompraloYa Shop" },
    desc: { es: "Solución de E-Commerce completa enfocada en reducir el abandono de carrito con una experiencia de checkout fluida.", en: "Complete E-commerce solution focused on reducing cart abandonment with a seamless checkout experience." }
  },
  {
    category: "dev",
    github: "#",
    image: "/assets/mockup_aurum.png",
    link: "https://aurum-estetica.netlify.app",
    title: { es: "Aurum Estética", en: "Aurum Esthetics" },
    desc: { es: "Embudo de ventas digital para centro de estética, diseñado estratégicamente para agendar citas y capturar datos de clientes.", en: "Digital sales funnel for an esthetics center, strategically designed to book appointments and capture client data." }
  },
  {
    category: "dev",
    github: "#",
    image: "/assets/mockup_titan.png",
    link: "https://titan-forge.netlify.app",
    title: { es: "Titan Forge", en: "Titan Forge" },
    desc: { es: "Portal web de membresías para gimnasio, optimizado para móvil y enfocado en la adquisición rápida de nuevos socios.", en: "Membership web portal for a gym, mobile-optimized and focused on rapid new member acquisition." }
  },
  {
    category: "dev",
    github: "#",
    image: "/assets/mockup_atelier.png",
    link: "https://atelierisabella.netlify.app",
    title: { es: "Atelier Isabella", en: "Atelier Isabella" },
    desc: { es: "Portafolio premium y vitrina digital, utilizando estética minimalista para destacar servicios de alto valor.", en: "Premium portfolio and digital showcase, using minimalist aesthetics to highlight high-value services." }
  },
  // Social Media Manager Projects
  {
    category: "social",
    image: "/assets/logos/crea_8_logotipos_202603180039.jpeg",
    link: "gallery",
    galleryImages: [
      "/assets/logos/Eight_professional_business_202603180026.jpeg",
      "/assets/logos/crea_8_logotipos_202603180038.jpeg",
      "/assets/logos/crea_8_logotipos_202603180039 (1).jpeg",
      "/assets/logos/crea_8_logotipos_202603180039 (2).jpeg",
      "/assets/logos/crea_8_logotipos_202603180039.jpeg",
      "/assets/logos/crea_8_logotipos_202603180043 (1).jpeg",
      "/assets/logos/crea_8_logotipos_202603180043.jpeg",
    ],
    title: { es: "Diseño de Logos", en: "Logo Design" },
    desc: { es: "Creación de identidad visual y logotipos profesionales para marcas y emprendimientos.", en: "Professional logo and visual identity creation for brands and businesses." }
  },
  {
    category: "social",
    image: "/assets/social_bk_post.jpg",
    link: "gallery",
    galleryImages: [
      "/assets/social_bk_post.jpg",
      "/assets/social_bk_flyer_1.jpg",
      "/assets/social_bk_flyer_2.jpg",
      "/assets/social_mcdonalds.jpg",
    ],
    title: { es: "Flyers Publicitarios", en: "Advertising Flyers" },
    desc: { es: "Diseño de flyers promocionales y piezas gráficas para distintas marcas, eventos y campañas publicitarias.", en: "Design of promotional flyers and graphic pieces for various brands, events, and advertising campaigns." }
  },
  {
    category: "social",
    image: "/assets/modelos/Woman_fitness_collage_202603172112.jpeg",
    link: "gallery",
    galleryImages: [
      "/assets/modelos/Man_smoking_in_cafe_f8eb074a8a.jpeg",
      "/assets/modelos/Person_with_tattoos_holding_face_44ce9e2086.jpeg",
      "/assets/modelos/Woman_fitness_collage_202603172112.jpeg",
      "/assets/modelos/Woman_in_black_202603171820.jpeg",
      "/assets/modelos/Woman_in_black_202603171935.jpeg",
      "/assets/modelos/Woman_smiling_in_202603172111.jpeg",
      "/assets/modelos/Young_adult_sitting_loading_dock_a0fa1fde0e.jpeg",
    ],
    title: { es: "Fotos de Modelos", en: "Model Photos" },
    desc: { es: "Fotografía y dirección de arte para modelos, lookbooks y campañas de moda con enfoque editorial.", en: "Photography and art direction for models, lookbooks, and fashion campaigns with editorial focus." }
  },
  {
    category: "social",
    image: "/assets/productos/Cosmetic_bottle_floating_202603171755.jpeg",
    link: "gallery",
    galleryImages: [
      "/assets/productos/Cocktail_with_fresh_202603171806.jpeg",
      "/assets/productos/Cosmetic_bottle_floating_202603171755.jpeg",
      "/assets/productos/Cosmetic_bottle_floating_202603171756.jpeg",
      "/assets/productos/Cosmetic_cream_jar_202603171759.jpeg",
      "/assets/productos/Fernet_con_Coca_202603171806.jpeg",
      "/assets/productos/Lip_gloss_splash_202603171804.jpeg",
      "/assets/productos/Miniature_skiers_on_202603172114.jpeg",
      "/assets/productos/Niña_sonriendo_sosteniendo_202603172019.jpeg",
      "/assets/productos/Strawberry_energy_drink_202603171822.jpeg",
      "/assets/productos/Woman_holding_pineapple_202603171801.jpeg",
    ],
    title: { es: "Fotos de Productos", en: "Product Photos" },
    desc: { es: "Fotografía de producto con foco en composición, iluminación y edición para e-commerce y catálogos.", en: "Product photography focused on composition, lighting, and editing for e-commerce and catalogs." }
  },
  {
    category: "social",
    image: "/assets/lifestyle/Woman_sitting_at_202603171818.jpeg",
    link: "gallery",
    galleryImages: [
      "/assets/lifestyle/Person_seated_on_patio_chair_2c902329dc.jpeg",
      "/assets/lifestyle/Singer_in_recording_202603172109.jpeg",
      "/assets/lifestyle/Woman_in_red_dress_clutch_99fdccbf5d.jpeg",
      "/assets/lifestyle/Woman_in_red_dress_clutch_cd596023da.jpeg",
      "/assets/lifestyle/Woman_sitting_at_202603171818.jpeg",
      "/assets/lifestyle/Woman_taking_mirror_202603172137.jpeg",
    ],
    title: { es: "Lifestyle & iPhone", en: "Lifestyle & iPhone" },
    desc: { es: "Captura de momentos auténticos y contenido estético 'casual' optimizado para redes sociales utilizando dispositivos móviles de alta gama.", en: "Capture of authentic moments and 'casual' aesthetic content optimized for social media using high-end mobile devices." }
  },
  {
    category: "social",
    image: "/assets/infografias/Infografía_tipos_de_202603172212.jpeg",
    link: "gallery",
    galleryImages: [
      "/assets/infografias/Calendario_2026_Hello_202603172302.jpeg",
      "/assets/infografias/Calendario_2026_Hello_202603172303.jpeg",
      "/assets/infografias/Gemini_Generated_Image_a3m6a8a3m6a8a3m6.png",
      "/assets/infografias/Gemini_Generated_Image_ldmgztldmgztldmg.png",
      "/assets/infografias/Infografia_sobre_Halloween_202603172306.jpeg",
      "/assets/infografias/Infografía_tipos_de_202603172212.jpeg",
    ],
    title: { es: "Infografías", en: "Infographics" },
    desc: { es: "Diseño de infografías informativas, calendarios y piezas visuales educativas para redes sociales.", en: "Design of informative infographics, calendars, and educational visual pieces for social media." }
  },
  // Extra - Music, Voice, Video
  {
    category: "media",
    image: "/assets/mockup_music.png",
    link: "gallery",
    youtubeIds: ["oodbsIXCb2A", "SVpwNSaaQ7k", "QCwv0_ZvFKw"],
    title: { es: "Producción Musical", en: "Music Production" },
    desc: { es: "Composición y producción de jingles, música de fondo e identidad sonora para marcas y proyectos audiovisuales.", en: "Composition and production of jingles, background music, and sonic identity for brands and audiovisual projects." }
  },
  {
    category: "media",
    image: "/assets/mockup_voice.png",
    link: "gallery",
    youtubeIds: ["Ohfy78llB8E", "osEP1P4A-KM"],
    title: { es: "Voz en Off", en: "Voice Over" },
    desc: { es: "Narraciones profesionales, doblaje y spots publicitarios con una identidad vocal única para potenciar cualquier mensaje.", en: "Professional voice-over for ads, corporate videos, e-learning, and social media content." }
  },
  {
    category: "media",
    image: "/assets/mockup_video.png",
    link: "gallery",
    youtubeIds: ["FM8jpEvwBRc", "C2yjyIduTMo", "TWHiTfw0Y54"],
    title: { es: "Edición de Video", en: "Video Editing" },
    desc: { es: "Montaje audiovisual, corrección de color y storytelling dinámico para redes sociales, publicidad y contenido institucional.", en: "Audiovisual editing, color correction, and dynamic storytelling for social media, advertising, and institutional content." }
  }
];
